### ISSUE TITLE
Same values for all the time

### ISSUE THREAD

**Issue by fajtak** [KarlFrederik/ulauncher-speedtest#2]
The speedtest measurement is done only once when the ULauncher is started and then the same values are being shown all the time the trigger word is used. It would be nice to do the measurement every single time the user asks for it.

**Comment by KarlFrederik** [comment]
I can do That, but it Would mean that every time you type in your keyword you would have to wait a while while the speed test runs. Would that be acceptable?

**Comment by fajtak** [comment]
Sure, I mean, you always have to wait to get results with any program/software/webpage of your choise. I just do not see the advantage to see results of hours or days old measurements. When I call this, I really want to know the recent speed because I have some troubles.

Thanks a lot.
Lukas

**Comment by KarlFrederik** [comment]
The old results were actually a bug i didn't even noticed. 
I am currently fixing it.

**Comment by KarlFrederik** [comment]
Fixed it, also "optimized it"
