### ISSUE TITLE
extension crashed

### ISSUE THREAD

**Issue by nuruddin-dev** [KarlFrederik/ulauncher-speedtest#4]
The extension crashed because it could not import module pynotifier. 
Try installing this module manually: pip3 install pynotifier --user and then restart Ulauncher.

**Comment by KarlFrederik** [comment]
I will look into this. In the meantime try: `pip3 install pynotifier --user ` or `sudo pip3 install pynotifier --user ` if the first one doesn't work. When did the problem occur? While installing with the installer script?

**Comment by luongson86** [comment]
> I will look into this. In the meantime try: `pip3 install pynotifier --user ` or `sudo pip3 install pynotifier --user ` if the first one doesn't work. When did the problem occur? While installing with the installer script?
It happent when restart Ulauncher after install this extension
and 
```
pip3 install pynotifier --user or sudo pip3 install pynotifier --user 
```
not wok

system say
```
ERROR: Could not find a version that satisfies the requirement pynotifier (from versions: none)
ERROR: No matching distribution found for pynotifier
```
![image](https://user-images.githubusercontent.com/20305828/127547324-49400a56-eaf7-42ec-b411-3a2cbea6a043.png)

**Comment by luongson86** [comment]
In the end, I was wrong!

There is no note on the Ulauncher Extensions website that must run installscript.sh before adding this extension to configuration.
Now it work perfect

p/s: please note that there is only py-notifier package, not pynotifier package 

Thank you for creating a great extension @KarlFrederik

**Comment by KarlFrederik** [comment]
> There is no note on the Ulauncher Extensions website that must run installscript.sh before adding this extension to configuration.

There should be one now.

> p/s: please note that there is only py-notifier package, not pynotifier package

The crash reports are done automatically from Ulauncher. I can't edit them, unfortunately.
