### ISSUE TITLE
The extension crashed because it could not import module speedtest. 

### ISSUE THREAD

**Issue by shay79il** [KarlFrederik/ulauncher-speedtest#7]
> pip install pynotifier --user 
ERROR: Could not find a version that satisfies the requirement pynotifier (from versions: none)
ERROR: No matching distribution found for pynotifier

**Comment by KarlFrederik** [comment]
Your PIP version might be deprecated. Try updating pip. This isn't a problem with the installscript, but a PIP problem. It might be deprecated or some old version. Or try `pip install py-notifier`
